version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_PORT}:5432"

  admin:
    build: ./services/admin
    depends_on:
      - postgres
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${ADMIN_PORT}:8001"

  users:
    build: ./services/users
    depends_on:
      - postgres
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${USERS_PORT}:8002"

  gateway:
    build: ./gateway
    depends_on:
      - admin
      - users
    env_file: .env
    ports:
      - "${GATEWAY_PORT}:8080"

volumes:
  pgdata:
